// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/AlarmData.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WInfoMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PvSn   int64 `protobuf:"varint,1,opt,name=pv_sn,json=pvSn,proto3" json:"pv_sn,omitempty"` // PV serial number
	WCode  int32 `protobuf:"varint,2,opt,name=WCode,proto3" json:"WCode,omitempty"`           // WCode identifier
	WNum   int32 `protobuf:"varint,3,opt,name=WNum,proto3" json:"WNum,omitempty"`             // WNum value
	WTime1 int32 `protobuf:"varint,4,opt,name=WTime1,proto3" json:"WTime1,omitempty"`         // First timestamp value
	WTime2 int32 `protobuf:"varint,5,opt,name=WTime2,proto3" json:"WTime2,omitempty"`         // Second timestamp value
	WData1 int32 `protobuf:"varint,6,opt,name=WData1,proto3" json:"WData1,omitempty"`         // First data value
	WData2 int32 `protobuf:"varint,7,opt,name=WData2,proto3" json:"WData2,omitempty"`         // Second data value
}

func (x *WInfoMO) Reset() {
	*x = WInfoMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AlarmData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WInfoMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WInfoMO) ProtoMessage() {}

func (x *WInfoMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AlarmData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WInfoMO.ProtoReflect.Descriptor instead.
func (*WInfoMO) Descriptor() ([]byte, []int) {
	return file_protos_AlarmData_proto_rawDescGZIP(), []int{0}
}

func (x *WInfoMO) GetPvSn() int64 {
	if x != nil {
		return x.PvSn
	}
	return 0
}

func (x *WInfoMO) GetWCode() int32 {
	if x != nil {
		return x.WCode
	}
	return 0
}

func (x *WInfoMO) GetWNum() int32 {
	if x != nil {
		return x.WNum
	}
	return 0
}

func (x *WInfoMO) GetWTime1() int32 {
	if x != nil {
		return x.WTime1
	}
	return 0
}

func (x *WInfoMO) GetWTime2() int32 {
	if x != nil {
		return x.WTime2
	}
	return 0
}

func (x *WInfoMO) GetWData1() int32 {
	if x != nil {
		return x.WData1
	}
	return 0
}

func (x *WInfoMO) GetWData2() int32 {
	if x != nil {
		return x.WData2
	}
	return 0
}

type WInfoReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn  string     `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"` // DTU serial number
	Time   int32      `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`               // Timestamp of the request
	MWInfo []*WInfoMO `protobuf:"bytes,3,rep,name=mWInfo,proto3" json:"mWInfo,omitempty"`            // WInfoMO data array
}

func (x *WInfoReqDTO) Reset() {
	*x = WInfoReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AlarmData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WInfoReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WInfoReqDTO) ProtoMessage() {}

func (x *WInfoReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AlarmData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WInfoReqDTO.ProtoReflect.Descriptor instead.
func (*WInfoReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_AlarmData_proto_rawDescGZIP(), []int{1}
}

func (x *WInfoReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *WInfoReqDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WInfoReqDTO) GetMWInfo() []*WInfoMO {
	if x != nil {
		return x.MWInfo
	}
	return nil
}

type WInfoResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeYmdHms string `protobuf:"bytes,1,opt,name=time_ymd_hms,json=timeYmdHms,proto3" json:"time_ymd_hms,omitempty"` // Timestamp in the format YMD_HMS
	ErrorCode  int32  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`     // Error code indicator
	Offset     int32  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                            // Offset value
	Time       int32  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                                // Timestamp value
}

func (x *WInfoResDTO) Reset() {
	*x = WInfoResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AlarmData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WInfoResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WInfoResDTO) ProtoMessage() {}

func (x *WInfoResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AlarmData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WInfoResDTO.ProtoReflect.Descriptor instead.
func (*WInfoResDTO) Descriptor() ([]byte, []int) {
	return file_protos_AlarmData_proto_rawDescGZIP(), []int{2}
}

func (x *WInfoResDTO) GetTimeYmdHms() string {
	if x != nil {
		return x.TimeYmdHms
	}
	return ""
}

func (x *WInfoResDTO) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WInfoResDTO) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WInfoResDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type WWVDataReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn      string `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"`                 // DTU serial number
	Time       int32  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                               // Timestamp of the request
	PackageNub int32  `protobuf:"varint,3,opt,name=package_nub,json=packageNub,proto3" json:"package_nub,omitempty"` // Package number
	PackageNow int32  `protobuf:"varint,4,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"` // Current package number
	PvSn       int64  `protobuf:"varint,5,opt,name=pv_sn,json=pvSn,proto3" json:"pv_sn,omitempty"`                   // PV serial number
	WCode      int32  `protobuf:"varint,6,opt,name=WCode,proto3" json:"WCode,omitempty"`                             // WCode identifier
	WNum       int32  `protobuf:"varint,7,opt,name=WNum,proto3" json:"WNum,omitempty"`                               // WNum value
	WTime1     int32  `protobuf:"varint,8,opt,name=WTime1,proto3" json:"WTime1,omitempty"`                           // First timestamp value
	WVDataL    int32  `protobuf:"varint,9,opt,name=WVDataL,proto3" json:"WVDataL,omitempty"`                         // Length of WWVData
	WPos       int32  `protobuf:"varint,10,opt,name=WPos,proto3" json:"WPos,omitempty"`                              // WPos value
	MWVData    string `protobuf:"bytes,11,opt,name=mWVData,proto3" json:"mWVData,omitempty"`                         // WWVData string
}

func (x *WWVDataReqDTO) Reset() {
	*x = WWVDataReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AlarmData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WWVDataReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WWVDataReqDTO) ProtoMessage() {}

func (x *WWVDataReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AlarmData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WWVDataReqDTO.ProtoReflect.Descriptor instead.
func (*WWVDataReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_AlarmData_proto_rawDescGZIP(), []int{3}
}

func (x *WWVDataReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *WWVDataReqDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *WWVDataReqDTO) GetPackageNub() int32 {
	if x != nil {
		return x.PackageNub
	}
	return 0
}

func (x *WWVDataReqDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *WWVDataReqDTO) GetPvSn() int64 {
	if x != nil {
		return x.PvSn
	}
	return 0
}

func (x *WWVDataReqDTO) GetWCode() int32 {
	if x != nil {
		return x.WCode
	}
	return 0
}

func (x *WWVDataReqDTO) GetWNum() int32 {
	if x != nil {
		return x.WNum
	}
	return 0
}

func (x *WWVDataReqDTO) GetWTime1() int32 {
	if x != nil {
		return x.WTime1
	}
	return 0
}

func (x *WWVDataReqDTO) GetWVDataL() int32 {
	if x != nil {
		return x.WVDataL
	}
	return 0
}

func (x *WWVDataReqDTO) GetWPos() int32 {
	if x != nil {
		return x.WPos
	}
	return 0
}

func (x *WWVDataReqDTO) GetMWVData() string {
	if x != nil {
		return x.MWVData
	}
	return ""
}

type WWVDataResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeYmdHms string `protobuf:"bytes,1,opt,name=time_ymd_hms,json=timeYmdHms,proto3" json:"time_ymd_hms,omitempty"` // Timestamp in the format YMD_HMS
	PackageNow int32  `protobuf:"varint,2,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"`  // Current package number
	ErrorCode  int32  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`     // Error code indicator
	Offset     int32  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                            // Offset value
	Time       int32  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`                                // Timestamp value
}

func (x *WWVDataResDTO) Reset() {
	*x = WWVDataResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AlarmData_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WWVDataResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WWVDataResDTO) ProtoMessage() {}

func (x *WWVDataResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AlarmData_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WWVDataResDTO.ProtoReflect.Descriptor instead.
func (*WWVDataResDTO) Descriptor() ([]byte, []int) {
	return file_protos_AlarmData_proto_rawDescGZIP(), []int{4}
}

func (x *WWVDataResDTO) GetTimeYmdHms() string {
	if x != nil {
		return x.TimeYmdHms
	}
	return ""
}

func (x *WWVDataResDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *WWVDataResDTO) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WWVDataResDTO) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WWVDataResDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_protos_AlarmData_proto protoreflect.FileDescriptor

var file_protos_AlarmData_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x57, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x4f, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x76, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x76, 0x53, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x57, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x57, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x57,
	0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x54, 0x69, 0x6d, 0x65, 0x31, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x54, 0x69, 0x6d, 0x65, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x57,
	0x54, 0x69, 0x6d, 0x65, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x54, 0x69,
	0x6d, 0x65, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x44, 0x61, 0x74, 0x61, 0x31, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x44, 0x61, 0x74, 0x61, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x57,
	0x44, 0x61, 0x74, 0x61, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x44, 0x61,
	0x74, 0x61, 0x32, 0x22, 0x5a, 0x0a, 0x0b, 0x57, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x44,
	0x54, 0x4f, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x74, 0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x64, 0x74, 0x75, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x06, 0x6d, 0x57, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x57, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x4f, 0x52, 0x06, 0x6d, 0x57, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x7a, 0x0a, 0x0b, 0x57, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x44, 0x54, 0x4f, 0x12, 0x20,
	0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x79, 0x6d, 0x64, 0x5f, 0x68, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x59, 0x6d, 0x64, 0x48, 0x6d, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x9b, 0x02, 0x0a, 0x0d,
	0x57, 0x57, 0x56, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x44, 0x54, 0x4f, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x74, 0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x74, 0x75, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x76,
	0x5f, 0x73, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x76, 0x53, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x57, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x57, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x57, 0x4e, 0x75, 0x6d, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x57, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x54, 0x69,
	0x6d, 0x65, 0x31, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x54, 0x69, 0x6d, 0x65,
	0x31, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x56, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x57, 0x56, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x57,
	0x50, 0x6f, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x57, 0x50, 0x6f, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x57, 0x56, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x57, 0x56, 0x44, 0x61, 0x74, 0x61, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x57, 0x57,
	0x56, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x44, 0x54, 0x4f, 0x12, 0x20, 0x0a, 0x0c, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x79, 0x6d, 0x64, 0x5f, 0x68, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x59, 0x6d, 0x64, 0x48, 0x6d, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x23, 0x5a, 0x0f, 0x68, 0x6f, 0x79,
	0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0xaa, 0x02, 0x0f, 0x48,
	0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_AlarmData_proto_rawDescOnce sync.Once
	file_protos_AlarmData_proto_rawDescData = file_protos_AlarmData_proto_rawDesc
)

func file_protos_AlarmData_proto_rawDescGZIP() []byte {
	file_protos_AlarmData_proto_rawDescOnce.Do(func() {
		file_protos_AlarmData_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_AlarmData_proto_rawDescData)
	})
	return file_protos_AlarmData_proto_rawDescData
}

var file_protos_AlarmData_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_AlarmData_proto_goTypes = []any{
	(*WInfoMO)(nil),       // 0: WInfoMO
	(*WInfoReqDTO)(nil),   // 1: WInfoReqDTO
	(*WInfoResDTO)(nil),   // 2: WInfoResDTO
	(*WWVDataReqDTO)(nil), // 3: WWVDataReqDTO
	(*WWVDataResDTO)(nil), // 4: WWVDataResDTO
}
var file_protos_AlarmData_proto_depIdxs = []int32{
	0, // 0: WInfoReqDTO.mWInfo:type_name -> WInfoMO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_AlarmData_proto_init() }
func file_protos_AlarmData_proto_init() {
	if File_protos_AlarmData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_AlarmData_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WInfoMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AlarmData_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WInfoReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AlarmData_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WInfoResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AlarmData_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WWVDataReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AlarmData_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*WWVDataResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_AlarmData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_AlarmData_proto_goTypes,
		DependencyIndexes: file_protos_AlarmData_proto_depIdxs,
		MessageInfos:      file_protos_AlarmData_proto_msgTypes,
	}.Build()
	File_protos_AlarmData_proto = out.File
	file_protos_AlarmData_proto_rawDesc = nil
	file_protos_AlarmData_proto_goTypes = nil
	file_protos_AlarmData_proto_depIdxs = nil
}
