// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/AppGetHistED.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppGetHistEDResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cp   int32  `protobuf:"varint,1,opt,name=cp,proto3" json:"cp,omitempty"`     // Control point identifier
	Oft  int32  `protobuf:"varint,2,opt,name=oft,proto3" json:"oft,omitempty"`   // Offset value
	Time uint32 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"` // Timestamp of the response
}

func (x *AppGetHistEDResDTO) Reset() {
	*x = AppGetHistEDResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AppGetHistED_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppGetHistEDResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetHistEDResDTO) ProtoMessage() {}

func (x *AppGetHistEDResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AppGetHistED_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetHistEDResDTO.ProtoReflect.Descriptor instead.
func (*AppGetHistEDResDTO) Descriptor() ([]byte, []int) {
	return file_protos_AppGetHistED_proto_rawDescGZIP(), []int{0}
}

func (x *AppGetHistEDResDTO) GetCp() int32 {
	if x != nil {
		return x.Cp
	}
	return 0
}

func (x *AppGetHistEDResDTO) GetOft() int32 {
	if x != nil {
		return x.Oft
	}
	return 0
}

func (x *AppGetHistEDResDTO) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type APPEnergyInfoMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ed    uint32 `protobuf:"varint,1,opt,name=ed,proto3" json:"ed,omitempty"`                    // Energy data
	RTime uint32 `protobuf:"varint,2,opt,name=r_time,json=rTime,proto3" json:"r_time,omitempty"` // Relative timestamp
}

func (x *APPEnergyInfoMO) Reset() {
	*x = APPEnergyInfoMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AppGetHistED_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APPEnergyInfoMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APPEnergyInfoMO) ProtoMessage() {}

func (x *APPEnergyInfoMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AppGetHistED_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APPEnergyInfoMO.ProtoReflect.Descriptor instead.
func (*APPEnergyInfoMO) Descriptor() ([]byte, []int) {
	return file_protos_AppGetHistED_proto_rawDescGZIP(), []int{1}
}

func (x *APPEnergyInfoMO) GetEd() uint32 {
	if x != nil {
		return x.Ed
	}
	return 0
}

func (x *APPEnergyInfoMO) GetRTime() uint32 {
	if x != nil {
		return x.RTime
	}
	return 0
}

type AppGetHistEDReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn    int64              `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`      // Serial number
	Oft   int32              `protobuf:"varint,2,opt,name=oft,proto3" json:"oft,omitempty"`    // Offset value
	Time  uint32             `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`  // Timestamp of the request
	Energ []*APPEnergyInfoMO `protobuf:"bytes,4,rep,name=energ,proto3" json:"energ,omitempty"` // APPEnergyInfoMO data array
}

func (x *AppGetHistEDReqDTO) Reset() {
	*x = AppGetHistEDReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_AppGetHistED_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppGetHistEDReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetHistEDReqDTO) ProtoMessage() {}

func (x *AppGetHistEDReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_AppGetHistED_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetHistEDReqDTO.ProtoReflect.Descriptor instead.
func (*AppGetHistEDReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_AppGetHistED_proto_rawDescGZIP(), []int{2}
}

func (x *AppGetHistEDReqDTO) GetSn() int64 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *AppGetHistEDReqDTO) GetOft() int32 {
	if x != nil {
		return x.Oft
	}
	return 0
}

func (x *AppGetHistEDReqDTO) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AppGetHistEDReqDTO) GetEnerg() []*APPEnergyInfoMO {
	if x != nil {
		return x.Energ
	}
	return nil
}

var File_protos_AppGetHistED_proto protoreflect.FileDescriptor

var file_protos_AppGetHistED_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x41, 0x70, 0x70, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x45, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x41,
	0x70, 0x70, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x45, 0x44, 0x52, 0x65, 0x73, 0x44, 0x54,
	0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6f, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0f, 0x41, 0x50, 0x50, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x72, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x45,
	0x44, 0x52, 0x65, 0x71, 0x44, 0x54, 0x4f, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x73, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x66, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x05, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41,
	0x50, 0x50, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x4f, 0x52, 0x05,
	0x65, 0x6e, 0x65, 0x72, 0x67, 0x42, 0x23, 0x5a, 0x0f, 0x68, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65,
	0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0xaa, 0x02, 0x0f, 0x48, 0x6f, 0x79, 0x6d, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_AppGetHistED_proto_rawDescOnce sync.Once
	file_protos_AppGetHistED_proto_rawDescData = file_protos_AppGetHistED_proto_rawDesc
)

func file_protos_AppGetHistED_proto_rawDescGZIP() []byte {
	file_protos_AppGetHistED_proto_rawDescOnce.Do(func() {
		file_protos_AppGetHistED_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_AppGetHistED_proto_rawDescData)
	})
	return file_protos_AppGetHistED_proto_rawDescData
}

var file_protos_AppGetHistED_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_AppGetHistED_proto_goTypes = []any{
	(*AppGetHistEDResDTO)(nil), // 0: AppGetHistEDResDTO
	(*APPEnergyInfoMO)(nil),    // 1: APPEnergyInfoMO
	(*AppGetHistEDReqDTO)(nil), // 2: AppGetHistEDReqDTO
}
var file_protos_AppGetHistED_proto_depIdxs = []int32{
	1, // 0: AppGetHistEDReqDTO.energ:type_name -> APPEnergyInfoMO
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_AppGetHistED_proto_init() }
func file_protos_AppGetHistED_proto_init() {
	if File_protos_AppGetHistED_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_AppGetHistED_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AppGetHistEDResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AppGetHistED_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*APPEnergyInfoMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_AppGetHistED_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AppGetHistEDReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_AppGetHistED_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_AppGetHistED_proto_goTypes,
		DependencyIndexes: file_protos_AppGetHistED_proto_depIdxs,
		MessageInfos:      file_protos_AppGetHistED_proto_msgTypes,
	}.Build()
	File_protos_AppGetHistED_proto = out.File
	file_protos_AppGetHistED_proto_rawDesc = nil
	file_protos_AppGetHistED_proto_goTypes = nil
	file_protos_AppGetHistED_proto_depIdxs = nil
}
