// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/CommandPB.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time         int32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`                                        // Timestamp of the response
	Action       int32    `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`                                    // Action code indicating the type of command
	DevKind      int32    `protobuf:"varint,3,opt,name=dev_kind,json=devKind,proto3" json:"dev_kind,omitempty"`                   // Device kind information
	PackageNub   int32    `protobuf:"varint,4,opt,name=package_nub,json=packageNub,proto3" json:"package_nub,omitempty"`          // Total number of packages expected
	PackageNow   int32    `protobuf:"varint,5,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"`          // Current package number
	Tid          int64    `protobuf:"varint,6,opt,name=tid,proto3" json:"tid,omitempty"`                                          // Transaction ID?
	Data         string   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`                                         // Additional data payload
	EsToSn       []string `protobuf:"bytes,8,rep,name=es_to_sn,json=esToSn,proto3" json:"es_to_sn,omitempty"`                     // List of ES serial numbers
	MiToSn       []int64  `protobuf:"varint,9,rep,packed,name=mi_to_sn,json=miToSn,proto3" json:"mi_to_sn,omitempty"`             // List of MI serial numbers
	SystemTotalA int32    `protobuf:"varint,10,opt,name=system_total_a,json=systemTotalA,proto3" json:"system_total_a,omitempty"` // System total for category A
	SystemTotalB int32    `protobuf:"varint,11,opt,name=system_total_b,json=systemTotalB,proto3" json:"system_total_b,omitempty"` // System total for category B
	SystemTotalC int32    `protobuf:"varint,12,opt,name=system_total_c,json=systemTotalC,proto3" json:"system_total_c,omitempty"` // System total for category C
	MiSnItemA    []int64  `protobuf:"varint,13,rep,packed,name=mi_sn_item_a,json=miSnItemA,proto3" json:"mi_sn_item_a,omitempty"` // List of MI serial numbers for category A
	MiSnItemB    []int64  `protobuf:"varint,14,rep,packed,name=mi_sn_item_b,json=miSnItemB,proto3" json:"mi_sn_item_b,omitempty"` // List of MI serial numbers for category B
	MiSnItemC    []int64  `protobuf:"varint,15,rep,packed,name=mi_sn_item_c,json=miSnItemC,proto3" json:"mi_sn_item_c,omitempty"` // List of MI serial numbers for category C
}

func (x *CommandResDTO) Reset() {
	*x = CommandResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResDTO) ProtoMessage() {}

func (x *CommandResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResDTO.ProtoReflect.Descriptor instead.
func (*CommandResDTO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{0}
}

func (x *CommandResDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CommandResDTO) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *CommandResDTO) GetDevKind() int32 {
	if x != nil {
		return x.DevKind
	}
	return 0
}

func (x *CommandResDTO) GetPackageNub() int32 {
	if x != nil {
		return x.PackageNub
	}
	return 0
}

func (x *CommandResDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *CommandResDTO) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *CommandResDTO) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CommandResDTO) GetEsToSn() []string {
	if x != nil {
		return x.EsToSn
	}
	return nil
}

func (x *CommandResDTO) GetMiToSn() []int64 {
	if x != nil {
		return x.MiToSn
	}
	return nil
}

func (x *CommandResDTO) GetSystemTotalA() int32 {
	if x != nil {
		return x.SystemTotalA
	}
	return 0
}

func (x *CommandResDTO) GetSystemTotalB() int32 {
	if x != nil {
		return x.SystemTotalB
	}
	return 0
}

func (x *CommandResDTO) GetSystemTotalC() int32 {
	if x != nil {
		return x.SystemTotalC
	}
	return 0
}

func (x *CommandResDTO) GetMiSnItemA() []int64 {
	if x != nil {
		return x.MiSnItemA
	}
	return nil
}

func (x *CommandResDTO) GetMiSnItemB() []int64 {
	if x != nil {
		return x.MiSnItemB
	}
	return nil
}

func (x *CommandResDTO) GetMiSnItemC() []int64 {
	if x != nil {
		return x.MiSnItemC
	}
	return nil
}

type CommandReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn      string `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"`                 // Data Terminal Unit (DTU) serial number
	Time       int32  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                               // Timestamp of the request
	Action     int32  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`                           // Action code indicating the type of command
	PackageNow int32  `protobuf:"varint,4,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"` // Current package number
	ErrCode    int32  `protobuf:"varint,5,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`          // Error code (if any)
	Tid        int64  `protobuf:"varint,6,opt,name=tid,proto3" json:"tid,omitempty"`                                 // Transaction ID
}

func (x *CommandReqDTO) Reset() {
	*x = CommandReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReqDTO) ProtoMessage() {}

func (x *CommandReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReqDTO.ProtoReflect.Descriptor instead.
func (*CommandReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{1}
}

func (x *CommandReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *CommandReqDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CommandReqDTO) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *CommandReqDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *CommandReqDTO) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *CommandReqDTO) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type ESOperatingStatusMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsSn         string `protobuf:"bytes,1,opt,name=es_sn,json=esSn,proto3" json:"es_sn,omitempty"`                          // ES serial number
	ProgressRate int32  `protobuf:"varint,2,opt,name=progress_rate,json=progressRate,proto3" json:"progress_rate,omitempty"` // Progress rate of the operation
}

func (x *ESOperatingStatusMO) Reset() {
	*x = ESOperatingStatusMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESOperatingStatusMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESOperatingStatusMO) ProtoMessage() {}

func (x *ESOperatingStatusMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESOperatingStatusMO.ProtoReflect.Descriptor instead.
func (*ESOperatingStatusMO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{2}
}

func (x *ESOperatingStatusMO) GetEsSn() string {
	if x != nil {
		return x.EsSn
	}
	return ""
}

func (x *ESOperatingStatusMO) GetProgressRate() int32 {
	if x != nil {
		return x.ProgressRate
	}
	return 0
}

type MIOperatingStatusMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MiSn         int64 `protobuf:"varint,1,opt,name=mi_sn,json=miSn,proto3" json:"mi_sn,omitempty"`                         // MI serial number
	ProgressRate int32 `protobuf:"varint,2,opt,name=progress_rate,json=progressRate,proto3" json:"progress_rate,omitempty"` // Progress rate of the operation
}

func (x *MIOperatingStatusMO) Reset() {
	*x = MIOperatingStatusMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MIOperatingStatusMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MIOperatingStatusMO) ProtoMessage() {}

func (x *MIOperatingStatusMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MIOperatingStatusMO.ProtoReflect.Descriptor instead.
func (*MIOperatingStatusMO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{3}
}

func (x *MIOperatingStatusMO) GetMiSn() int64 {
	if x != nil {
		return x.MiSn
	}
	return 0
}

func (x *MIOperatingStatusMO) GetProgressRate() int32 {
	if x != nil {
		return x.ProgressRate
	}
	return 0
}

type MIErrorStatusMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MiSn      int64 `protobuf:"varint,1,opt,name=mi_sn,json=miSn,proto3" json:"mi_sn,omitempty"`                // MI serial number
	ErrorCode int64 `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // Error code associated with the MI
}

func (x *MIErrorStatusMO) Reset() {
	*x = MIErrorStatusMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MIErrorStatusMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MIErrorStatusMO) ProtoMessage() {}

func (x *MIErrorStatusMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MIErrorStatusMO.ProtoReflect.Descriptor instead.
func (*MIErrorStatusMO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{4}
}

func (x *MIErrorStatusMO) GetMiSn() int64 {
	if x != nil {
		return x.MiSn
	}
	return 0
}

func (x *MIErrorStatusMO) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type ESSucStatusMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsSn string `protobuf:"bytes,1,opt,name=es_sn,json=esSn,proto3" json:"es_sn,omitempty"` // ES serial number
}

func (x *ESSucStatusMO) Reset() {
	*x = ESSucStatusMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESSucStatusMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESSucStatusMO) ProtoMessage() {}

func (x *ESSucStatusMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESSucStatusMO.ProtoReflect.Descriptor instead.
func (*ESSucStatusMO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{5}
}

func (x *ESSucStatusMO) GetEsSn() string {
	if x != nil {
		return x.EsSn
	}
	return ""
}

type ESErrorStatusMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsSn      string `protobuf:"bytes,1,opt,name=es_sn,json=esSn,proto3" json:"es_sn,omitempty"`                 // ES serial number
	ErrorCode int64  `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // Error code associated with the ES
}

func (x *ESErrorStatusMO) Reset() {
	*x = ESErrorStatusMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ESErrorStatusMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESErrorStatusMO) ProtoMessage() {}

func (x *ESErrorStatusMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESErrorStatusMO.ProtoReflect.Descriptor instead.
func (*ESErrorStatusMO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{6}
}

func (x *ESErrorStatusMO) GetEsSn() string {
	if x != nil {
		return x.EsSn
	}
	return ""
}

func (x *ESErrorStatusMO) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type CommandStatusReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn              string                 `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"`                                         // Data Terminal Unit (DTU) serial number
	Time               int32                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                                                       // Timestamp of the request
	Action             int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`                                                   // Action code indicating the type of command
	PackageNub         int32                  `protobuf:"varint,4,opt,name=package_nub,json=packageNub,proto3" json:"package_nub,omitempty"`                         // Total number of packages expected
	PackageNow         int32                  `protobuf:"varint,5,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"`                         // Current package number
	Tid                int64                  `protobuf:"varint,6,opt,name=tid,proto3" json:"tid,omitempty"`                                                         // Transaction ID
	EsSnsSucs          []string               `protobuf:"bytes,7,rep,name=es_sns_sucs,json=esSnsSucs,proto3" json:"es_sns_sucs,omitempty"`                           // List of ES serial numbers with successful execution
	MiSnsSucs          []int64                `protobuf:"varint,8,rep,packed,name=mi_sns_sucs,json=miSnsSucs,proto3" json:"mi_sns_sucs,omitempty"`                   // List of MI serial numbers with successful execution
	EsSnsFailds        []string               `protobuf:"bytes,9,rep,name=es_sns_failds,json=esSnsFailds,proto3" json:"es_sns_failds,omitempty"`                     // List of ES serial numbers with failed execution
	MiSnsFailds        []int64                `protobuf:"varint,10,rep,packed,name=mi_sns_failds,json=miSnsFailds,proto3" json:"mi_sns_failds,omitempty"`            // List of MI serial numbers with failed execution
	EsMOperatingStatus []*ESOperatingStatusMO `protobuf:"bytes,11,rep,name=es_mOperatingStatus,json=esMOperatingStatus,proto3" json:"es_mOperatingStatus,omitempty"` // List of ES operating statuses
	MiMOperatingStatus []*MIOperatingStatusMO `protobuf:"bytes,12,rep,name=mi_mOperatingStatus,json=miMOperatingStatus,proto3" json:"mi_mOperatingStatus,omitempty"` // List of MI operating statuses
	MiMErrorStatus     []*MIErrorStatusMO     `protobuf:"bytes,13,rep,name=mi_mErrorStatus,json=miMErrorStatus,proto3" json:"mi_mErrorStatus,omitempty"`             // List of MI error statuses
	EsMSucStatus       []*ESSucStatusMO       `protobuf:"bytes,14,rep,name=es_mSucStatus,json=esMSucStatus,proto3" json:"es_mSucStatus,omitempty"`                   // List of successful ES statuses
	EsMErrorStatus     []*ESErrorStatusMO     `protobuf:"bytes,15,rep,name=es_mErrorStatus,json=esMErrorStatus,proto3" json:"es_mErrorStatus,omitempty"`             // List of error ES statuses
}

func (x *CommandStatusReqDTO) Reset() {
	*x = CommandStatusReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandStatusReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatusReqDTO) ProtoMessage() {}

func (x *CommandStatusReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatusReqDTO.ProtoReflect.Descriptor instead.
func (*CommandStatusReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{7}
}

func (x *CommandStatusReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *CommandStatusReqDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CommandStatusReqDTO) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *CommandStatusReqDTO) GetPackageNub() int32 {
	if x != nil {
		return x.PackageNub
	}
	return 0
}

func (x *CommandStatusReqDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *CommandStatusReqDTO) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *CommandStatusReqDTO) GetEsSnsSucs() []string {
	if x != nil {
		return x.EsSnsSucs
	}
	return nil
}

func (x *CommandStatusReqDTO) GetMiSnsSucs() []int64 {
	if x != nil {
		return x.MiSnsSucs
	}
	return nil
}

func (x *CommandStatusReqDTO) GetEsSnsFailds() []string {
	if x != nil {
		return x.EsSnsFailds
	}
	return nil
}

func (x *CommandStatusReqDTO) GetMiSnsFailds() []int64 {
	if x != nil {
		return x.MiSnsFailds
	}
	return nil
}

func (x *CommandStatusReqDTO) GetEsMOperatingStatus() []*ESOperatingStatusMO {
	if x != nil {
		return x.EsMOperatingStatus
	}
	return nil
}

func (x *CommandStatusReqDTO) GetMiMOperatingStatus() []*MIOperatingStatusMO {
	if x != nil {
		return x.MiMOperatingStatus
	}
	return nil
}

func (x *CommandStatusReqDTO) GetMiMErrorStatus() []*MIErrorStatusMO {
	if x != nil {
		return x.MiMErrorStatus
	}
	return nil
}

func (x *CommandStatusReqDTO) GetEsMSucStatus() []*ESSucStatusMO {
	if x != nil {
		return x.EsMSucStatus
	}
	return nil
}

func (x *CommandStatusReqDTO) GetEsMErrorStatus() []*ESErrorStatusMO {
	if x != nil {
		return x.EsMErrorStatus
	}
	return nil
}

type CommandStatusResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time       int32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`                               // Timestamp of the response
	Action     int32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`                           // Action code indicating the type of command
	PackageNow int32 `protobuf:"varint,3,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"` // Current package number
	Tid        int64 `protobuf:"varint,4,opt,name=tid,proto3" json:"tid,omitempty"`                                 // Transaction ID
	ErrCode    int32 `protobuf:"varint,5,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`          // Error code (if any)
}

func (x *CommandStatusResDTO) Reset() {
	*x = CommandStatusResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_CommandPB_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandStatusResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStatusResDTO) ProtoMessage() {}

func (x *CommandStatusResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_CommandPB_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStatusResDTO.ProtoReflect.Descriptor instead.
func (*CommandStatusResDTO) Descriptor() ([]byte, []int) {
	return file_protos_CommandPB_proto_rawDescGZIP(), []int{8}
}

func (x *CommandStatusResDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CommandStatusResDTO) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *CommandStatusResDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *CommandStatusResDTO) GetTid() int64 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *CommandStatusResDTO) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

var File_protos_CommandPB_proto protoreflect.FileDescriptor

var file_protos_CommandPB_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x50, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x03, 0x0a, 0x0d, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x44, 0x54, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x5f, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x76, 0x4b, 0x69, 0x6e,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x62,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e,
	0x75, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x4e, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x08, 0x65, 0x73, 0x5f,
	0x74, 0x6f, 0x5f, 0x73, 0x6e, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x54,
	0x6f, 0x53, 0x6e, 0x12, 0x18, 0x0a, 0x08, 0x6d, 0x69, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x6e, 0x18,
	0x09, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x69, 0x54, 0x6f, 0x53, 0x6e, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x41, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x62, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x12,
	0x1f, 0x0a, 0x0c, 0x6d, 0x69, 0x5f, 0x73, 0x6e, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x18,
	0x0d, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x53, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x41,
	0x12, 0x1f, 0x0a, 0x0c, 0x6d, 0x69, 0x5f, 0x73, 0x6e, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x62,
	0x18, 0x0e, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x53, 0x6e, 0x49, 0x74, 0x65, 0x6d,
	0x42, 0x12, 0x1f, 0x0a, 0x0c, 0x6d, 0x69, 0x5f, 0x73, 0x6e, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x63, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x69, 0x53, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x43, 0x22, 0xa0, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x44, 0x54, 0x4f, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x74, 0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x74, 0x75, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x74, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x13, 0x45, 0x53, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x12, 0x13, 0x0a, 0x05,
	0x65, 0x73, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x73, 0x53,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x13, 0x4d, 0x49, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x12, 0x13, 0x0a,
	0x05, 0x6d, 0x69, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x69,
	0x53, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x61, 0x74, 0x65, 0x22, 0x45, 0x0a, 0x0f, 0x4d, 0x49, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x12, 0x13, 0x0a, 0x05, 0x6d, 0x69,
	0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d, 0x69, 0x53, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x24,
	0x0a, 0x0d, 0x45, 0x53, 0x53, 0x75, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x12,
	0x13, 0x0a, 0x05, 0x65, 0x73, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x65, 0x73, 0x53, 0x6e, 0x22, 0x45, 0x0a, 0x0f, 0x45, 0x53, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x12, 0x13, 0x0a, 0x05, 0x65, 0x73, 0x5f, 0x73, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x73, 0x53, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xed, 0x04, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x44, 0x54, 0x4f, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x74, 0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x74, 0x75, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x75, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x65, 0x73,
	0x5f, 0x73, 0x6e, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x73, 0x53, 0x6e, 0x73, 0x53, 0x75, 0x63, 0x73, 0x12, 0x1e, 0x0a, 0x0b, 0x6d, 0x69,
	0x5f, 0x73, 0x6e, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x09, 0x6d, 0x69, 0x53, 0x6e, 0x73, 0x53, 0x75, 0x63, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x73,
	0x5f, 0x73, 0x6e, 0x73, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x65, 0x73, 0x53, 0x6e, 0x73, 0x46, 0x61, 0x69, 0x6c, 0x64, 0x73, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x69, 0x5f, 0x73, 0x6e, 0x73, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x64, 0x73, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x69, 0x53, 0x6e, 0x73, 0x46, 0x61, 0x69, 0x6c,
	0x64, 0x73, 0x12, 0x45, 0x0a, 0x13, 0x65, 0x73, 0x5f, 0x6d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x45, 0x53, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4d, 0x4f, 0x52, 0x12, 0x65, 0x73, 0x4d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x45, 0x0a, 0x13, 0x6d, 0x69, 0x5f,
	0x6d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x49, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x52, 0x12, 0x6d, 0x69,
	0x4d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x39, 0x0a, 0x0f, 0x6d, 0x69, 0x5f, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x49, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x52, 0x0e, 0x6d, 0x69, 0x4d,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x33, 0x0a, 0x0d, 0x65,
	0x73, 0x5f, 0x6d, 0x53, 0x75, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x53, 0x53, 0x75, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4d, 0x4f, 0x52, 0x0c, 0x65, 0x73, 0x4d, 0x53, 0x75, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x39, 0x0a, 0x0f, 0x65, 0x73, 0x5f, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x53, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x4f, 0x52, 0x0e, 0x65, 0x73, 0x4d,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x13,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x44, 0x54, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74,
	0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x23, 0x5a,
	0x0f, 0x68, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0xaa, 0x02, 0x0f, 0x48, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_CommandPB_proto_rawDescOnce sync.Once
	file_protos_CommandPB_proto_rawDescData = file_protos_CommandPB_proto_rawDesc
)

func file_protos_CommandPB_proto_rawDescGZIP() []byte {
	file_protos_CommandPB_proto_rawDescOnce.Do(func() {
		file_protos_CommandPB_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_CommandPB_proto_rawDescData)
	})
	return file_protos_CommandPB_proto_rawDescData
}

var file_protos_CommandPB_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_CommandPB_proto_goTypes = []any{
	(*CommandResDTO)(nil),       // 0: CommandResDTO
	(*CommandReqDTO)(nil),       // 1: CommandReqDTO
	(*ESOperatingStatusMO)(nil), // 2: ESOperatingStatusMO
	(*MIOperatingStatusMO)(nil), // 3: MIOperatingStatusMO
	(*MIErrorStatusMO)(nil),     // 4: MIErrorStatusMO
	(*ESSucStatusMO)(nil),       // 5: ESSucStatusMO
	(*ESErrorStatusMO)(nil),     // 6: ESErrorStatusMO
	(*CommandStatusReqDTO)(nil), // 7: CommandStatusReqDTO
	(*CommandStatusResDTO)(nil), // 8: CommandStatusResDTO
}
var file_protos_CommandPB_proto_depIdxs = []int32{
	2, // 0: CommandStatusReqDTO.es_mOperatingStatus:type_name -> ESOperatingStatusMO
	3, // 1: CommandStatusReqDTO.mi_mOperatingStatus:type_name -> MIOperatingStatusMO
	4, // 2: CommandStatusReqDTO.mi_mErrorStatus:type_name -> MIErrorStatusMO
	5, // 3: CommandStatusReqDTO.es_mSucStatus:type_name -> ESSucStatusMO
	6, // 4: CommandStatusReqDTO.es_mErrorStatus:type_name -> ESErrorStatusMO
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_CommandPB_proto_init() }
func file_protos_CommandPB_proto_init() {
	if File_protos_CommandPB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_CommandPB_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CommandResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CommandReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ESOperatingStatusMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MIOperatingStatusMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MIErrorStatusMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ESSucStatusMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ESErrorStatusMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CommandStatusReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_CommandPB_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CommandStatusResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_CommandPB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_CommandPB_proto_goTypes,
		DependencyIndexes: file_protos_CommandPB_proto_depIdxs,
		MessageInfos:      file_protos_CommandPB_proto_msgTypes,
	}.Build()
	File_protos_CommandPB_proto = out.File
	file_protos_CommandPB_proto_rawDesc = nil
	file_protos_CommandPB_proto_goTypes = nil
	file_protos_CommandPB_proto_depIdxs = nil
}
