// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/GPSTData.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STValMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DfltVal int32 `protobuf:"varint,2,opt,name=dflt_val,json=dfltVal,proto3" json:"dflt_val,omitempty"`
	DfltTim int32 `protobuf:"varint,3,opt,name=dflt_tim,json=dfltTim,proto3" json:"dflt_tim,omitempty"`
	RsltVal int32 `protobuf:"varint,4,opt,name=rslt_val,json=rsltVal,proto3" json:"rslt_val,omitempty"`
	RsltTim int32 `protobuf:"varint,5,opt,name=rslt_tim,json=rsltTim,proto3" json:"rslt_tim,omitempty"`
}

func (x *STValMO) Reset() {
	*x = STValMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_GPSTData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STValMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STValMO) ProtoMessage() {}

func (x *STValMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_GPSTData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STValMO.ProtoReflect.Descriptor instead.
func (*STValMO) Descriptor() ([]byte, []int) {
	return file_protos_GPSTData_proto_rawDescGZIP(), []int{0}
}

func (x *STValMO) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *STValMO) GetDfltVal() int32 {
	if x != nil {
		return x.DfltVal
	}
	return 0
}

func (x *STValMO) GetDfltTim() int32 {
	if x != nil {
		return x.DfltTim
	}
	return 0
}

func (x *STValMO) GetRsltVal() int32 {
	if x != nil {
		return x.RsltVal
	}
	return 0
}

func (x *STValMO) GetRsltTim() int32 {
	if x != nil {
		return x.RsltTim
	}
	return 0
}

type GPSTValMO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PvSn     int64    `protobuf:"varint,1,opt,name=pv_sn,json=pvSn,proto3" json:"pv_sn,omitempty"`
	Ver      int32    `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	St       int32    `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`
	Gpf      int32    `protobuf:"varint,4,opt,name=gpf,proto3" json:"gpf,omitempty"`
	GpfVer   int32    `protobuf:"varint,5,opt,name=gpf_ver,json=gpfVer,proto3" json:"gpf_ver,omitempty"`
	Hv1Stval *STValMO `protobuf:"bytes,6,opt,name=hv1_stval,json=hv1Stval,proto3" json:"hv1_stval,omitempty"`
	Lv1Stval *STValMO `protobuf:"bytes,7,opt,name=lv1_stval,json=lv1Stval,proto3" json:"lv1_stval,omitempty"`
	Hv2Stval *STValMO `protobuf:"bytes,8,opt,name=hv2_stval,json=hv2Stval,proto3" json:"hv2_stval,omitempty"`
	Lv2Stval *STValMO `protobuf:"bytes,9,opt,name=lv2_stval,json=lv2Stval,proto3" json:"lv2_stval,omitempty"`
	Hf1Stval *STValMO `protobuf:"bytes,10,opt,name=hf1_stval,json=hf1Stval,proto3" json:"hf1_stval,omitempty"`
	Lf1Stval *STValMO `protobuf:"bytes,11,opt,name=lf1_stval,json=lf1Stval,proto3" json:"lf1_stval,omitempty"`
	Hf2Stval *STValMO `protobuf:"bytes,12,opt,name=hf2_stval,json=hf2Stval,proto3" json:"hf2_stval,omitempty"`
	Lf2Stval *STValMO `protobuf:"bytes,13,opt,name=lf2_stval,json=lf2Stval,proto3" json:"lf2_stval,omitempty"`
}

func (x *GPSTValMO) Reset() {
	*x = GPSTValMO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_GPSTData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPSTValMO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSTValMO) ProtoMessage() {}

func (x *GPSTValMO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_GPSTData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSTValMO.ProtoReflect.Descriptor instead.
func (*GPSTValMO) Descriptor() ([]byte, []int) {
	return file_protos_GPSTData_proto_rawDescGZIP(), []int{1}
}

func (x *GPSTValMO) GetPvSn() int64 {
	if x != nil {
		return x.PvSn
	}
	return 0
}

func (x *GPSTValMO) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *GPSTValMO) GetSt() int32 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *GPSTValMO) GetGpf() int32 {
	if x != nil {
		return x.Gpf
	}
	return 0
}

func (x *GPSTValMO) GetGpfVer() int32 {
	if x != nil {
		return x.GpfVer
	}
	return 0
}

func (x *GPSTValMO) GetHv1Stval() *STValMO {
	if x != nil {
		return x.Hv1Stval
	}
	return nil
}

func (x *GPSTValMO) GetLv1Stval() *STValMO {
	if x != nil {
		return x.Lv1Stval
	}
	return nil
}

func (x *GPSTValMO) GetHv2Stval() *STValMO {
	if x != nil {
		return x.Hv2Stval
	}
	return nil
}

func (x *GPSTValMO) GetLv2Stval() *STValMO {
	if x != nil {
		return x.Lv2Stval
	}
	return nil
}

func (x *GPSTValMO) GetHf1Stval() *STValMO {
	if x != nil {
		return x.Hf1Stval
	}
	return nil
}

func (x *GPSTValMO) GetLf1Stval() *STValMO {
	if x != nil {
		return x.Lf1Stval
	}
	return nil
}

func (x *GPSTValMO) GetHf2Stval() *STValMO {
	if x != nil {
		return x.Hf2Stval
	}
	return nil
}

func (x *GPSTValMO) GetLf2Stval() *STValMO {
	if x != nil {
		return x.Lf2Stval
	}
	return nil
}

type GPSTReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn      string       `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"`
	Time       int32        `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	PackageNub int32        `protobuf:"varint,3,opt,name=package_nub,json=packageNub,proto3" json:"package_nub,omitempty"`
	PackageNow int32        `protobuf:"varint,4,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"`
	MGPSTInfo  []*GPSTValMO `protobuf:"bytes,5,rep,name=mGPSTInfo,proto3" json:"mGPSTInfo,omitempty"`
}

func (x *GPSTReqDTO) Reset() {
	*x = GPSTReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_GPSTData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPSTReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSTReqDTO) ProtoMessage() {}

func (x *GPSTReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_GPSTData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSTReqDTO.ProtoReflect.Descriptor instead.
func (*GPSTReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_GPSTData_proto_rawDescGZIP(), []int{2}
}

func (x *GPSTReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *GPSTReqDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *GPSTReqDTO) GetPackageNub() int32 {
	if x != nil {
		return x.PackageNub
	}
	return 0
}

func (x *GPSTReqDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *GPSTReqDTO) GetMGPSTInfo() []*GPSTValMO {
	if x != nil {
		return x.MGPSTInfo
	}
	return nil
}

type GPSTResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YmdHms     string `protobuf:"bytes,1,opt,name=ymd_hms,json=ymdHms,proto3" json:"ymd_hms,omitempty"`
	Offset     int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	PackageNow int32  `protobuf:"varint,3,opt,name=package_now,json=packageNow,proto3" json:"package_now,omitempty"`
	ErrCode    int32  `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Time       int32  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GPSTResDTO) Reset() {
	*x = GPSTResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_GPSTData_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPSTResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSTResDTO) ProtoMessage() {}

func (x *GPSTResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_GPSTData_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSTResDTO.ProtoReflect.Descriptor instead.
func (*GPSTResDTO) Descriptor() ([]byte, []int) {
	return file_protos_GPSTData_proto_rawDescGZIP(), []int{3}
}

func (x *GPSTResDTO) GetYmdHms() string {
	if x != nil {
		return x.YmdHms
	}
	return ""
}

func (x *GPSTResDTO) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GPSTResDTO) GetPackageNow() int32 {
	if x != nil {
		return x.PackageNow
	}
	return 0
}

func (x *GPSTResDTO) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GPSTResDTO) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_protos_GPSTData_proto protoreflect.FileDescriptor

var file_protos_GPSTData_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x47, 0x50, 0x53, 0x54, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x53, 0x54, 0x56, 0x61,
	0x6c, 0x4d, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x66, 0x6c, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x66, 0x6c, 0x74, 0x56,
	0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x66, 0x6c, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x66, 0x6c, 0x74, 0x54, 0x69, 0x6d, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x73, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x72, 0x73, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x73, 0x6c, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x73, 0x6c, 0x74,
	0x54, 0x69, 0x6d, 0x22, 0xa5, 0x03, 0x0a, 0x09, 0x47, 0x50, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d,
	0x4f, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x76, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x76, 0x53, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x70, 0x66, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x67, 0x70, 0x66, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x70,
	0x66, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x70, 0x66,
	0x56, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x09, 0x68, 0x76, 0x31, 0x5f, 0x73, 0x74, 0x76, 0x61, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f,
	0x52, 0x08, 0x68, 0x76, 0x31, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x6c, 0x76,
	0x31, 0x5f, 0x73, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x08, 0x6c, 0x76, 0x31, 0x53, 0x74, 0x76, 0x61,
	0x6c, 0x12, 0x25, 0x0a, 0x09, 0x68, 0x76, 0x32, 0x5f, 0x73, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x08,
	0x68, 0x76, 0x32, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x6c, 0x76, 0x32, 0x5f,
	0x73, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54,
	0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x08, 0x6c, 0x76, 0x32, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x12,
	0x25, 0x0a, 0x09, 0x68, 0x66, 0x31, 0x5f, 0x73, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x08, 0x68, 0x66,
	0x31, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x6c, 0x66, 0x31, 0x5f, 0x73, 0x74,
	0x76, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61,
	0x6c, 0x4d, 0x4f, 0x52, 0x08, 0x6c, 0x66, 0x31, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a,
	0x09, 0x68, 0x66, 0x32, 0x5f, 0x73, 0x74, 0x76, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x08, 0x68, 0x66, 0x32, 0x53,
	0x74, 0x76, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x6c, 0x66, 0x32, 0x5f, 0x73, 0x74, 0x76, 0x61,
	0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x54, 0x56, 0x61, 0x6c, 0x4d,
	0x4f, 0x52, 0x08, 0x6c, 0x66, 0x32, 0x53, 0x74, 0x76, 0x61, 0x6c, 0x22, 0xa3, 0x01, 0x0a, 0x0a,
	0x47, 0x50, 0x53, 0x54, 0x52, 0x65, 0x71, 0x44, 0x54, 0x4f, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x74,
	0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x74, 0x75, 0x53,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x62, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x77, 0x12, 0x28, 0x0a, 0x09, 0x6d, 0x47, 0x50, 0x53, 0x54,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x47, 0x50, 0x53,
	0x54, 0x56, 0x61, 0x6c, 0x4d, 0x4f, 0x52, 0x09, 0x6d, 0x47, 0x50, 0x53, 0x54, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x47, 0x50, 0x53, 0x54, 0x52, 0x65, 0x73, 0x44, 0x54, 0x4f,
	0x12, 0x17, 0x0a, 0x07, 0x79, 0x6d, 0x64, 0x5f, 0x68, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x79, 0x6d, 0x64, 0x48, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x77, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x42, 0x23, 0x5a, 0x0f, 0x68, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0xaa, 0x02, 0x0f, 0x48, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_GPSTData_proto_rawDescOnce sync.Once
	file_protos_GPSTData_proto_rawDescData = file_protos_GPSTData_proto_rawDesc
)

func file_protos_GPSTData_proto_rawDescGZIP() []byte {
	file_protos_GPSTData_proto_rawDescOnce.Do(func() {
		file_protos_GPSTData_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_GPSTData_proto_rawDescData)
	})
	return file_protos_GPSTData_proto_rawDescData
}

var file_protos_GPSTData_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_GPSTData_proto_goTypes = []any{
	(*STValMO)(nil),    // 0: STValMO
	(*GPSTValMO)(nil),  // 1: GPSTValMO
	(*GPSTReqDTO)(nil), // 2: GPSTReqDTO
	(*GPSTResDTO)(nil), // 3: GPSTResDTO
}
var file_protos_GPSTData_proto_depIdxs = []int32{
	0, // 0: GPSTValMO.hv1_stval:type_name -> STValMO
	0, // 1: GPSTValMO.lv1_stval:type_name -> STValMO
	0, // 2: GPSTValMO.hv2_stval:type_name -> STValMO
	0, // 3: GPSTValMO.lv2_stval:type_name -> STValMO
	0, // 4: GPSTValMO.hf1_stval:type_name -> STValMO
	0, // 5: GPSTValMO.lf1_stval:type_name -> STValMO
	0, // 6: GPSTValMO.hf2_stval:type_name -> STValMO
	0, // 7: GPSTValMO.lf2_stval:type_name -> STValMO
	1, // 8: GPSTReqDTO.mGPSTInfo:type_name -> GPSTValMO
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_protos_GPSTData_proto_init() }
func file_protos_GPSTData_proto_init() {
	if File_protos_GPSTData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_GPSTData_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*STValMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_GPSTData_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GPSTValMO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_GPSTData_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GPSTReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_GPSTData_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GPSTResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_GPSTData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_GPSTData_proto_goTypes,
		DependencyIndexes: file_protos_GPSTData_proto_depIdxs,
		MessageInfos:      file_protos_GPSTData_proto_msgTypes,
	}.Build()
	File_protos_GPSTData_proto = out.File
	file_protos_GPSTData_proto_rawDesc = nil
	file_protos_GPSTData_proto_goTypes = nil
	file_protos_GPSTData_proto_depIdxs = nil
}
