// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: protos/NetworkInfo.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkInfoReqDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DtuSn        string `protobuf:"bytes,1,opt,name=dtu_sn,json=dtuSn,proto3" json:"dtu_sn,omitempty"`                         // DTU serial number
	Time         uint32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                                       // Timestamp of the request
	NetSetMod    int32  `protobuf:"varint,3,opt,name=net_set_mod,json=netSetMod,proto3" json:"net_set_mod,omitempty"`          // Network setting mode
	NetSetTime   int32  `protobuf:"varint,4,opt,name=net_set_time,json=netSetTime,proto3" json:"net_set_time,omitempty"`       // Network setting time
	NetSetState  int32  `protobuf:"varint,5,opt,name=net_set_state,json=netSetState,proto3" json:"net_set_state,omitempty"`    // Network setting state
	NetWorkMod   int32  `protobuf:"varint,6,opt,name=net_work_mod,json=netWorkMod,proto3" json:"net_work_mod,omitempty"`       // Network working mode
	NetWorkTime  int32  `protobuf:"varint,7,opt,name=net_work_time,json=netWorkTime,proto3" json:"net_work_time,omitempty"`    // Network working time
	Csq          int32  `protobuf:"varint,8,opt,name=csq,proto3" json:"csq,omitempty"`                                         // Carrier Signal Quality (CSQ)
	NetWorkState int32  `protobuf:"varint,9,opt,name=net_work_state,json=netWorkState,proto3" json:"net_work_state,omitempty"` // Network working state
	ApSetState   int32  `protobuf:"varint,10,opt,name=ap_set_state,json=apSetState,proto3" json:"ap_set_state,omitempty"`      // Access Point (AP) setting state
}

func (x *NetworkInfoReqDTO) Reset() {
	*x = NetworkInfoReqDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_NetworkInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfoReqDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfoReqDTO) ProtoMessage() {}

func (x *NetworkInfoReqDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NetworkInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfoReqDTO.ProtoReflect.Descriptor instead.
func (*NetworkInfoReqDTO) Descriptor() ([]byte, []int) {
	return file_protos_NetworkInfo_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkInfoReqDTO) GetDtuSn() string {
	if x != nil {
		return x.DtuSn
	}
	return ""
}

func (x *NetworkInfoReqDTO) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetSetMod() int32 {
	if x != nil {
		return x.NetSetMod
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetSetTime() int32 {
	if x != nil {
		return x.NetSetTime
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetSetState() int32 {
	if x != nil {
		return x.NetSetState
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetWorkMod() int32 {
	if x != nil {
		return x.NetWorkMod
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetWorkTime() int32 {
	if x != nil {
		return x.NetWorkTime
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetCsq() int32 {
	if x != nil {
		return x.Csq
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetNetWorkState() int32 {
	if x != nil {
		return x.NetWorkState
	}
	return 0
}

func (x *NetworkInfoReqDTO) GetApSetState() int32 {
	if x != nil {
		return x.ApSetState
	}
	return 0
}

type NetworkInfoResDTO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int32  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // Offset value for response
	Time   uint32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`     // Timestamp of the response
}

func (x *NetworkInfoResDTO) Reset() {
	*x = NetworkInfoResDTO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_NetworkInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfoResDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfoResDTO) ProtoMessage() {}

func (x *NetworkInfoResDTO) ProtoReflect() protoreflect.Message {
	mi := &file_protos_NetworkInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfoResDTO.ProtoReflect.Descriptor instead.
func (*NetworkInfoResDTO) Descriptor() ([]byte, []int) {
	return file_protos_NetworkInfo_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInfoResDTO) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NetworkInfoResDTO) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_protos_NetworkInfo_proto protoreflect.FileDescriptor

var file_protos_NetworkInfo_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x02, 0x0a, 0x11, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x44, 0x54, 0x4f,
	0x12, 0x15, 0x0a, 0x06, 0x64, 0x74, 0x75, 0x5f, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x64, 0x74, 0x75, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x6e,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6e, 0x65, 0x74, 0x53, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6e,
	0x65, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6e, 0x65, 0x74, 0x53, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x0d, 0x6e, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6d, 0x6f,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x4d, 0x6f, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x74, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e, 0x65, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73, 0x71, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x73, 0x71, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x74,
	0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x6e, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x20, 0x0a, 0x0c, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x70, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x3f, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x44, 0x54, 0x4f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x42, 0x23, 0x5a, 0x0f, 0x68, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0xaa, 0x02, 0x0f, 0x48, 0x6f, 0x79, 0x6d, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_NetworkInfo_proto_rawDescOnce sync.Once
	file_protos_NetworkInfo_proto_rawDescData = file_protos_NetworkInfo_proto_rawDesc
)

func file_protos_NetworkInfo_proto_rawDescGZIP() []byte {
	file_protos_NetworkInfo_proto_rawDescOnce.Do(func() {
		file_protos_NetworkInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_NetworkInfo_proto_rawDescData)
	})
	return file_protos_NetworkInfo_proto_rawDescData
}

var file_protos_NetworkInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_NetworkInfo_proto_goTypes = []any{
	(*NetworkInfoReqDTO)(nil), // 0: NetworkInfoReqDTO
	(*NetworkInfoResDTO)(nil), // 1: NetworkInfoResDTO
}
var file_protos_NetworkInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_NetworkInfo_proto_init() }
func file_protos_NetworkInfo_proto_init() {
	if File_protos_NetworkInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_NetworkInfo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkInfoReqDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_NetworkInfo_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkInfoResDTO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_NetworkInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_NetworkInfo_proto_goTypes,
		DependencyIndexes: file_protos_NetworkInfo_proto_depIdxs,
		MessageInfos:      file_protos_NetworkInfo_proto_msgTypes,
	}.Build()
	File_protos_NetworkInfo_proto = out.File
	file_protos_NetworkInfo_proto_rawDesc = nil
	file_protos_NetworkInfo_proto_goTypes = nil
	file_protos_NetworkInfo_proto_depIdxs = nil
}
