package common

// # App -> DTU start with 0xa3, responses start 0xa2
var CMD_HEADER = []byte{'H', 'M'}

var CMD_APP_INFO_DATA_RES_DTO = []byte{0xA3, 0x01}
var CMD_HB_RES_DTO = []byte{0xA3, 0x02}
var CMD_REAL_DATA_RES_DTO = []byte{0xA3, 0x03}
var CMD_W_INFO_RES_DTO = []byte{0xA3, 0x04}
var CMD_COMMAND_RES_DTO = []byte{0xA3, 0x05}
var CMD_COMMAND_STATUS_RES_DTO = []byte{0xA3, 0x06}
var CMD_DEV_CONFIG_FETCH_RES_DTO = []byte{0xA3, 0x07}
var CMD_DEV_CONFIG_PUT_RES_DTO = []byte{0xA3, 0x08}
var CMD_GET_CONFIG = []byte{0xA3, 0x09}
var CMD_SET_CONFIG = []byte{0xA3, 0x10}
var CMD_REAL_RES_DTO = []byte{0xA3, 0x11}
var CMD_GPST_RES_DTO = []byte{0xA3, 0x12}
var CMD_AUTO_SEARCH = []byte{0xA3, 0x13}
var CMD_NETWORK_INFO_RES = []byte{0xA3, 0x14}
var CMD_APP_GET_HIST_POWER_RES = []byte{0xA3, 0x15}
var CMD_APP_GET_HIST_ED_RES = []byte{0xA3, 0x16}
var CMD_HB_RES_DTO_ALT = []byte{0x83, 0x01}
var CMD_REGISTER_RES_DTO = []byte{0x83, 0x02}
var CMD_STORAGE_DATA_RES = []byte{0x83, 0x03}
var CMD_COMMAND_RES_DTO_2 = []byte{0x83, 0x05}
var CMD_COMMAND_STATUS_RES_DTO_2 = []byte{0x83, 0x06}
var CMD_DEV_CONFIG_FETCH_RES_DTO_2 = []byte{0x83, 0x07}
var CMD_DEV_CONFIG_PUT_RES_DTO_2 = []byte{0x83, 0x08}
var CMD_GET_CONFIG_RES = []byte{0xDB, 0x08}
var CMD_SET_CONFIG_RES = []byte{0xDB, 0x07}

var CMD_CLOUD_INFO_DATA_RES_DTO = []byte{0x23, 0x01}
var CMD_CLOUD_COMMAND_RES_DTO = []byte{0x23, 0x05}

const CMD_ACTION_MICRO_DEFAULT = 0

const CMD_ACTION_DTU_UPGRADE = 2

const CMD_ACTION_MI_REBOOT = 3

const CMD_ACTION_COLLECT_VERSION = 4

const CMD_ACTION_ANTI_THEFT_SETTING = 5

const CMD_ACTION_MI_START = 6

const CMD_ACTION_MI_SHUTDOWN = 7

const CMD_ACTION_LIMIT_POWER = 8

const CMD_ACTION_REFLUX_CONTROL = 9

const CMD_ACTION_CLEAN_GROUNDING_FAULT = 10

const CMD_ACTION_CT_SET = 11

const CMD_ACTION_MI_LOCK = 12

const CMD_ACTION_MI_UNLOCK = 13

const CMD_ACTION_SET_GRID_FILE = 14

const CMD_ACTION_UPGRADE_MI = 15

const CMD_ACTION_ID_NETWORKING = 16

const CMD_ACTION_REFLUX_NETWORKING = 17

const CMD_ACTION_STOP_CONTROLLER_CMD = 18

const CMD_ACTION_SET_WIFI_PASS = 19

const CMD_ACTION_SET_SVR_DNS_PORT = 20

const CMD_ACTION_SET_GPRS_APN = 21

const CMD_ACTION_ANTI_THEFT_CONTROL = 22

const CMD_ACTION_REPEATER_NETWORKING = 0

const CMD_ACTION_DTU_DEFAULT = 0

const CMD_ACTION_GATEWAY_DEFAULT = 0

const CMD_ACTION_METER_REVERSE = 49

const CMD_ACTION_ALARM_LIST = 50

const CMD_ACTION_GW_REBOOT = 4096

const CMD_ACTION_GW_RESET = 4097

const CMD_ACTION_GW_STOP_RUN = 4098

const CMD_ACTION_GW_COLLECT_REAL_DATA = 4099

const CMD_ACTION_GW_COLLECT_VER = 4100

const CMD_ACTION_GW_AUTO_NETWORKING = 4101

const CMD_ACTION_GW_UPGRADE = 4102

const CMD_ACTION_MICRO_MEMORY_SNAPSHOT = 53

const CMD_ACTION_MICRO_DATA_WAVE = 54

const CMD_ACTION_SET_485_PORT = 36

const CMD_ACTION_THREE_BALANCE_SET = 37

const CMD_ACTION_MI_GRID_PROTECT_SELF = 38

const CMD_ACTION_SUN_SPEC_CONFIG = 39

const CMD_ACTION_POWER_GENERATION_CORRECT = 40

const CMD_ACTION_GRID_FILE_READ = 41

const CMD_ACTION_CLEAN_WARN = 42

const CMD_ACTION_DRM_SETTING = 43

const CMD_ACTION_ES_CONFIG_MANAGER = 0

const CMD_ACTION_ES_USER_SETTING = 0

const CMD_ACTION_READ_MI_HU_WARN = 46

const CMD_ACTION_LIMIT_POWER_PF = 47

const CMD_ACTION_LIMIT_POWER_REACTIVE = 48

const CMD_ACTION_INV_BOOT_UP = 8193

const CMD_ACTION_INV_SHUTDOWN = 8194

const CMD_ACTION_INV_REBOOT = 8195

const CMD_ACTION_INV_RESET = 8196

const CMD_ACTION_INV_CLEAN_WARN = 8197

const CMD_ACTION_INV_CLEAN_HIS_DATA = 8198

const CMD_ACTION_INV_UPLOAD_REAL_DATA = 8199

const CMD_ACTION_INV_FIND_DEV = 8200

const CMD_ACTION_INV_BATTERY_MODE_CONFIG = 0

const CMD_ACTION_BMS_REBOOT = 8224

const CMD_ACTION_BMS_URGENT_CHARGING = 8225

const CMD_ACTION_BMS_BALANCE = 8208

const CMD_ACTION_INV_UPGRADE = 4112

const CMD_ACTION_BMS_UPGRADE = 4112
